import typing

def open(path: str, mode: str = "r") -> typing.IO: ...
def listdir(path: str) -> typing.Sequence[str]: ...
def isfile(path: str) -> bool: ...
def isdir(path: str) -> bool: ...
def islink(path: str) -> bool: ...
def readlink(path: str) -> str: ...
def getmode(path: str) -> int: ...
def getmtime(path: str) -> float: ...
